name: fluent_sdk
description: Package that provide a way to modularize features through a service locator.
version: 0.2.2
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_sdk

environment:
  sdk: "^3.3.0"

dependencies:
  get_it: ^7.7.0

dev_dependencies:
  test: ^1.25.5
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.3
  