name: fluent_sdk
description: Package that provide a way to modularize features through a service locator.
version: 0.1.1
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_sdk

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
  mocktail: ^0.3.0
  