name: fluent_localization
description: Package that allows you to translate the app texts
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_sdk:
    git:
      url: https://github.com/aosorio-avilez/flutter_fluent.git
      ref: fluent_sdk-v0.0.1
      path: packages/fluent_sdk
  fluent_localization_api:
    git:
      url: https://github.com/aosorio-avilez/flutter_fluent.git
      ref: fluent_localization-v0.0.1
      path: packages/fluent_localization/fluent_localization_api
  ez_localization: ^1.1.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  assets:
    - "assets/languages/"