name: fluent_networking
description: Package that provides a simple way to make http requests
version: 0.0.2+1
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_networking/fluent_networking

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  fluent_networking_api: ^0.0.3+1
  dio: ^5.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  flutter_loggy_dio: ^3.0.1

dev_dependencies:
  test: ^1.22.0
  very_good_analysis: ^4.0.0+1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  mocktail: ^0.3.0
