name: fluent_networking
description: Package that provides a simple way to make http requests
version: 0.4.0
resolution: workspace
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_networking/fluent_networking

environment:
  sdk: '^3.10.1'

dependencies:
  fluent_sdk: ^0.5.0
  fluent_networking_api: ^0.1.0
  dio: ^5.9.0
  equatable: ^2.0.5
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  test: ^1.22.0
  very_good_analysis: ^10.0.0
  mocktail: ^1.0.4
