name: fluent_networking
description: Package that provides a simple way to make http requests
version: 0.9.4
resolution: workspace
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_networking/fluent_networking

environment:
  sdk: '^3.9.2'

dependencies:
  fluent_sdk: ^0.8.0
  fluent_networking_api: ^0.4.0
  fluent_logger_api: ^0.0.4
  dio: ^5.9.1
  equatable: ^2.0.8

dev_dependencies:
  test: ^1.22.0
  very_good_analysis: ^10.0.0
  mocktail: ^1.0.4
