name: flutter_fluent

packages:
  - packages/*
  - packages/**

ignore:
  - packages/*/example
  - packages/**/example

scripts:
  install:
    run: melos exec "very_good packages get"
    description: Format dart files in all packages
  format:
    run: melos exec "dart format --set-exit-if-changed lib test"
    description: Format dart files in all packages
  analyze:
    run: melos exec --dir-exists="test" "flutter analyze --no-pub lib test"
    description: Analyze dart files in all packages
  test:
    run: melos exec --dir-exists="test" "very_good test -j 4 --optimization --min-coverage 100 --coverage --test-randomize-ordering-seed random"
    description: Run tests in all packages
  