name: flutter_fluent

packages:
  - packages/*
  - packages/**

scripts:
  format:
    run: melos exec "dart format --set-exit-if-changed lib test"
    description: Format dart files in all packages
  analyze:
    run: melos exec --dir-exists="test" "flutter analyze --no-pub lib test"
    description: Analyze dart files in all packages
  test:
    run: melos exec --dir-exists="test" "flutter test -j 4 --coverage --test-randomize-ordering-seed random"
    description: Run tests in all packages
  coverage:
    run: melos exec --dir-exists="test" "cover check --no-display-files --min-coverage 98"
    description: Run code coverage in all packages
  