name: flutter_fluent

environment:
  sdk: '^3.9.2'

workspace:
  - packages/fluent_environment/fluent_environment
  - packages/fluent_environment/fluent_environment/example
  - packages/fluent_environment/fluent_environment_api
  - packages/fluent_localization/fluent_localization
  - packages/fluent_localization/fluent_localization/example
  - packages/fluent_localization/fluent_localization_api
  - packages/fluent_logger/fluent_logger
  - packages/fluent_logger/fluent_logger/example
  - packages/fluent_logger/fluent_logger_api
  - packages/fluent_navigation/fluent_navigation
  - packages/fluent_navigation/fluent_navigation/example
  - packages/fluent_navigation/fluent_navigation_api
  - packages/fluent_networking/fluent_networking
  - packages/fluent_networking/fluent_networking/example
  - packages/fluent_networking/fluent_networking_api
  - packages/fluent_sdk
  - packages/fluent_sdk/example

dev_dependencies:
  melos: ^7.4.0

melos:
  command:
    bootstrap:
      runPubGetInParallel: true
  scripts:
    format:
      run: dart format . --set-exit-if-changed
      description: Format dart files in the workspace
    analyze:
      run: melos exec -c 4 --dir-exists="lib" --ignore="*example*" -- "flutter analyze --no-pub"
      description: Analyze core packages (excluding examples)
    test:
      run: melos exec -c 3 --dir-exists="test" --ignore="*example*" -- "flutter test --no-pub --coverage --test-randomize-ordering-seed random"
      description: Run core tests
    coverage:
      run: melos exec -c 6 --dir-exists="test" --ignore="*example*" -- "cover check --no-display-files --min-coverage 90"
      description: Run code coverage on core packages
