name: fluent_localization_api
description: A common interface for the fluent_localization package.
version: 1.0.2
resolution: workspace
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_localization/fluent_localization_api

environment:
  sdk: '^3.9.2'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^10.0.0