name: fluent_networking_api
description: A common interface for the fluent_networking package.
version: 0.2.0
resolution: workspace
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_networking/fluent_networking_api

environment:
  sdk: '^3.9.2'

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.5

dev_dependencies:
  very_good_analysis: ^10.0.0
