name: fluent_networking_api
description: Package that provides access to the networking api
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
  build_runner: ^2.3.3
  freezed: ^2.3.2
