include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
    public_member_api_docs: false
    one_member_abstracts: false