name: flutter_fluent_logger
description: Package that allows you to print different types of messages in console
version: 0.0.1
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_logger/fluent_logger

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_logger_api: ^0.0.1
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1