name: fluent_navigation
description: Package that provides a simple way to navigate within your app
version: 0.0.6
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_navigation/fluent_navigation

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_sdk: ^0.2.0
  fluent_navigation_api: ^0.0.4
  go_router: ^9.0.0
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  mocktail: ^0.3.0
