name: platform_environment
description: Package that provides a way to register your application environment and display the corresponding environment.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  platform_sdk:
    git:
      url: https://github.com/aosorio-avilez/flutter_platform.git
      ref: main
      path: packages/platform_sdk
  platform_environment_api:
    git:
      url: https://github.com/aosorio-avilez/flutter_platform.git
      ref: main
      path: packages/platform_environment/platform_environment_api
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1