name: platform_networking
description: Package that provides a simple way to make http requests
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  platform_sdk:
    git:
      url: https://github.com/aosorio-avilez/flutter_platform.git
      ref: main
      path: packages/platform_sdk
  platform_networking_api:
    git:
      url: https://github.com/aosorio-avilez/flutter_platform.git
      ref: main
      path: packages/platform_networking/platform_networking_api
  platform_environment_api:
    git:
      url: https://github.com/aosorio-avilez/flutter_platform.git
      ref: main
      path: packages/platform_environment/platform_environment_api
  dio: ^5.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  flutter_loggy_dio: ^3.0.1
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
  build_runner: ^2.3.3
  freezed: ^2.3.2
