name: fluent_logger_api
description: A common interface for the flutter_fluent_logger package.
version: 0.0.2+1
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_logger/fluent_logger_api

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  fluent_sdk: ^0.1.1

dev_dependencies:
  very_good_analysis: ^4.0.0+1
