# targets:
#   $default:
#     builders:
#       generators|annotations:
#         enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:fluent_environment/src/generators/builder.dart"
    builder_factories: [ "generateExtension"]
    build_extensions: { ".dart": ["extension_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
