name: fluent_navigation_api
description: A common interface for the fluent_navigation package.
version: 1.0.0
repository: https://github.com/aosorio-avilez/flutter_fluent/tree/main/packages/fluent_navigation/fluent_navigation_api

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
 very_good_analysis: ^5.1.0