name: flutter_fluent

on:
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: aosorio-avilez/flutter_fluent/.github/workflows/build.yaml@optimize-workflows