name: flutter_fluent

on:
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🐦 Setup FVM
        uses: leoafarias/fvm-action@v1
        with:
          version: stable

      - name: ⚙️ Install Tools
        run: ./.github/workflows/scripts/install-tools.sh

      - name: 📦 Install Dependencies
        run: melos bs

      - name: ✨ Check Formatting
        run: melos format

      - name: 🕵️ Analyze
        run: melos analyze

      - name: 🧪 Run Tests
        run: melos test
      
      - name: 📊 Check Coverage
        run: melos coverage