name: Test packages

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh

      - name: Install Dependencies
        run: melos bs

      - name: Format
        run: melos run format

      - name: Analyze
        run: melos run analyze

      - name: Test
        run: melos run test

      - name: Merge coverages reports
        run: melos run coverage

      - name: Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: '/coverage/filtered.lcov.info'
          min_coverage: 100
          exclude: '**/*.g.dart'
